### ISSUE TITLE
bat file error

### ISSUE THREAD

**Issue by jnyfiveoh** [gdiaz384/vEncode#1]
Pardon my ignorance,

When attempting to batch encode media files using ' vencode * '

I am encountering an error:

'vencode2' is not recognized as an internal or external command, operable program or batch file.

Did I miss a step or not install a prerequisite?

Also could you elaborate on the "drop and drag" function?

Thanks

**Comment by gdiaz384** [comment]
v1.0.3 is now out that fixes the vencode2 not found error.  It was there for debugging during development.

Here is a random article on drag and drop: https://www.computerhope.com/jargon/d/dragdrop.htm

For vencode, drag the video.mkv onto vencode.bat and it will encode the video using the default settings specified at the top of the file. Feel free to change the defaults to suit your needs. 

Note that drag and drop will not work if the path contains special or reserved characters (!, &,) and does not work for aencode yet.
